import "~/styles/globals.css";

import { type Metadata } from "next";
import { Inter, Noto_Sans_JP } from "next/font/google";

export const metadata: Metadata = {
  title: "Figma Clone",
  description: "Generated by Hito & Alessio",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-sans",
});

const notoSansJp = Noto_Sans_JP({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto-sans-jp",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja" className={`${inter.variable} ${notoSansJp.variable}`}>
      <body>{children}</body>
    </html>
  );
}
